# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  host: 127.0.0.1
  database: original_db_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  reconnect: true

development_temp:
  adapter: mysql2
  host: 127.0.0.1
  database: temp_db_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  reconnect: true


test:
  adapter: mysql2
  host: localhost
  database: original_db_test
  username: root
  password:
  pool: 5
  timeout: 5000
  reconnect: true

