# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)


development:
  adapter: mysql2
  host: 127.0.0.1
  database: admin_db_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  reconnect: true

development_dest:
  adapter: mysql2
  host: 127.0.0.1
  database: dest_db_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  reconnect: true

development_src:
  adapter: mysql2
  host: 127.0.0.1
  database: src_db_dev
  username: root
  password: 
  pool: 5
  timeout: 5000
  reconnect: true

